networks:
  app_network:
    driver: bridge

volumes:
  postgres_db_data:

services:
  birthdaysbot.api:
    image: ${DOCKER_REGISTRY-}birthdaysbotapi
    container_name: birthdaysbot.api
    build:
      context: .
      dockerfile: BirthdaysBot.API/Dockerfile
    networks:
        - app_network
  
  postgres_db:
    image: postgres:latest
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: fleshka5418
      POSTGRES_DB: birthdays
      POSTGRES_USER: roman
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network
    depends_on:
      - birthdaysbot.api

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml:ro
    ports:
      - "4040:4040"
    networks:
      - app_network
    depends_on:
      - nginx
